name: daviedeborah
description: "Convite de casamento de Davi & Deborah."

publish_to: 'none'

version: 1.1.11+12

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Gerenciamento de estado com MobX
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  
  # Ícones e UI
  google_fonts: ^6.3.3
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  photo_view: ^0.15.0
  web: ^1.1.1
  
  # Supabase
  supabase_flutter: ^2.12.0
  package_info_plus: ^9.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Build runner para geração de código MobX
  build_runner:
  mobx_codegen: ^2.7.4

flutter:

  uses-material-design: true